#!/usr/bin/env bash
# THIS FILE WAS AUTOMATICALLY GENERATED BY THE KNIME2Grid KNIME EXTENSION

# contains names of input ports that take filelists, separated by whitespace
INPUT_PORTS_WITH_FILELIST="@@INPUT_PORTS_WITH_FILELIST@@"
# contains names of output ports that generate filelists, separated by whitespace
OUTPUT_PORTS_WITH_FILELIST="@@OUTPUT_PORTS_WITH_FILELIST@@"
EXECUTABLE="@@EXECUTABLE@@"

if [ -n "$INPUT_PORTS_WITH_FILELIST" ]; then
	for input_port in ${INPUT_PORTS_WITH_FILELIST}; do
		echo "expanding ${input_port}"
		echo tar xfz ${input_port}
	done
fi

# execute the tool
echo "Executing: ${EXECUTABLE} $@"
${EXECUTABLE} $@

# compress the multi-file outputs and make sure to name the archive using port name and .tar.gz as extension
# see: com.workflowconversion.knime2grid.export.workflow.ConverterUtils.generateFileNameForExport(String, String, int) and
#      com.workflowconversion.knime2grid.export.workflow.impl.guse.GuseKnimeWorkflowExporter.fixPortName(Port)
if [ -n "$OUTPUT_PORTS_WITH_FILELIST" ]; then
	for output_port in ${OUTPUT_PORTS_WITH_FILELIST}; do
		echo "compressing outputs for ${output_port}"
		# the name of the port would be similar to foo.tar.gz, so we need to strip the .tar.gz (7 chars long) off the name
		# tools have been configured to output files using the following pattern:
		# 0_[foo].[bar], 1_[foo].[bar], ... 
		tar cfz ${output_port} *_${output_port:0:(-7)}
	done
fi