#!/usr/bin/env bash
# THIS FILE WAS AUTOMATICALLY GENERATED BY THE KNIME2GUSE KNIME EXTENSION

# gUSE will provide files named after this port name, e.g., foo_0, foo_1, ...
INPUT_BASE_NAME="@@INPUT_BASE_NAME@@"
OUTPUT_PORT_NAME="@@OUTPUT_PORT_NAME@@"

# Achtung: hoc non est verum scientia
tar cvfz ${OUTPUT_PORT_NAME} ${INPUT_BASE_NAME}_*
rm ${INPUT_BASE_NAME}_*