#!/usr/bin/env bash
# THIS FILE WAS AUTOMATICALLY GENERATED BY THE KNIME2GUSE KNIME EXTENSION

# we know that the port name refers to an archive (e.g., foo.bar.tar.gz)
# containing files named 0_foo.bar, 1_foo.bar, ...
PORT_NAME="@@PORT_NAME@@"

# why (-7), you ask, well, the length of the string ".tar.gz" is 7
BASE_NAME=${PORT_NAME:0:(-7)}			# e.g., foo.bar

# gUSE expects files from a generator to be named, e.g., foo.bar_0, foo.bar_1, ...

# "specialize in distributed systems", they said; "it will be fun", they said
tar xfz ${PORT_NAME}
for input_file in `tar tf ${PORT_NAME}`; do
	# rename N_foo.bar to foo.bar_N
	mv ${input_file} ${BASE_NAME}_`cut -d'_' -f1 <<< "${input_file}"`
done