#!/usr/bin/env bash
# THIS FILE WAS AUTOMATICALLY GENERATED BY THE KNIME2GUSE KNIME EXTENSION

# gUSE will provide files named after this port name, e.g., foo.bar_0, foo.bar_1, ...
BASE_PORT_NAME="@@BASE_PORT_NAME@@"		# e.g., foo.bar

# Achtung: hoc non est verum scientia
BASE_PORT_NAME_LENGTH=`expr length "${BASE_PORT_NAME}"`
for input_file in ${BASE_PORT_NAME}_*; do
	# we need to rename foo.bar_N to N_foo.bar, hold on to your butts:
	SUFFIX="${input_file:${BASE_PORT_NAME_LENGTH}}"
	mv ${input_file} ${SUFFIX:1}_${BASE_PORT_NAME}
done

# compress to, e.g, foo.bar.tar.gz and clean up
tar cfz ${BASE_PORT_NAME}.tar.gz *_${BASE_PORT_NAME}
rm *_${BASE_PORT_NAME}